{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saint-ops.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "saint-ops.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  {{- if .Values.mlflow.s3.enabled }}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.mlflow.s3.endpointUrl | quote }}
  {{- end }}
{{- end }}
