apiVersion: v1
kind: Pod
metadata:
  name: seed-pvc
  namespace: saint-dev
spec:
  restartPolicy: Never
  containers:
    - name: seed
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: storage
          mountPath: /mnt
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: saint-dev-saint-ops-storage
